name: Calculator CI Pipeline

on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: 
      - master

jobs:
  build_test_deploy:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Java Setup
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: test
      run: mvn clean test
      continue-on-error: true

    - name: Build JAR package (skip tests)
      run: mvn clean package -DskipTests
        
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: calculator-jar
        path: target/Calculator-1.0-SNAPSHOT.jar

        
    - name: Upload complete build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          target/*.jar
          target/classes/


